### PR TITLE
German Translation

### PR DESCRIPTION
**Pull request by scolast34**
German translation!
Using:
 - The polite German (Sie) instead of casual German (Du)
- Used the term "booking" for booking a table (DE: Tischreservation) to make a difference in German to book a hotel room

### CODE REVIEW

**Comment by NateWr** [comment]
Thanks @scolast34! I have a new version coming out soon with several new strings. Would you be willing to translate against a new .pot file when I generate it?

**Comment by scolast34** [comment]
Sure!

 

I’ll going to follow you

 

Cheers - Andy

 

Von: Nate Wright [mailto:notifications@github.com] 
Gesendet: Freitag, 2. Januar 2015 11:51
An: NateWr/restaurant-reservations
Cc: scolast34
Betreff: Re: [restaurant-reservations] German Translation (#9)

 

Thanks @scolast34 <https://github.com/scolast34> ! I have a new version coming out soon with several new strings. Would you be willing to translate against a new .pot file when I generate it?

**Comment by NateWr** [comment]
Hi @scolast34, I've generated a new .pot file in preparation for the next version release. Would you be willing to pull down the latest changes in ```master``` and share the new ```.po``` and ```.mo``` files you generate off this .pot? Then they'll ship with the next version of the plugin.

**Comment by scolast34** [comment]
Changed file names

**Comment by NateWr** [comment]
@scolast34 It looks like several dwsync.xml files got included in your last commit. If you have a chance before you go, can you strip them out?

**Comment by scolast34** [comment]
Hi 

You can delete them all.
They get created from DreamWaver ...
Sorry I forgot to delete them

Andi

**Comment by NateWr** [comment]
Are you able to push a new commit with them deleted or would you rather I just pick out your files and commit them myself?

**Comment by scolast34** [comment]
Please do it yourself!
I'm on a plane somewhere over the Arab Sea (Internet is a curtesy of Emirates)

Cheers
Andi

**Comment by NateWr** [comment]
Thanks @scolast34, I've got it all committed now in 909249ca08c27aadef177ef5498704e16ffe97e5. Much appreciated!

**Pull request closed without merging**
