### PR TITLE
Create rtbdomain-de_DE.mo

### PR DESCRIPTION
**Pull request by scolast34**
Updated with addtional strings

### CODE REVIEW

**Comment by NateWr** [comment]
Thanks! The latest version has changed the textdomain to restaurant-reservations. Can you change the filename to restaurant-reservations-de_DE.po then I'll merge this.

Also, do you generate a .mo file as well? I'll go ahead and ship that if you have it.

**Comment by scolast34** [comment]
Done!

 

I created a pull request.

Please let me know when I can load a beta version, so that I check the translations in the context.

 

Cheers 

 

Von: Nate Wright [mailto:notifications@github.com] 
Gesendet: Freitag, 2. Januar 2015 23:41
An: NateWr/restaurant-reservations
Cc: scolast34
Betreff: Re: [restaurant-reservations] Create rtbdomain-de_DE.mo (#10)

 

Thanks! The latest version has changed the textdomain to restaurant-reservations. Can you change the filename to restaurant-reservations-de_DE.po then I'll merge this.

Also, do you generate a .mo file as well? I'll go ahead and ship that if you have it.

**Comment by NateWr** [comment]
Thanks @scolast34. I loaded up the files on my end and it looks good. To test all the strings, you can download a copy of the [master branch](https://github.com/NateWr/restaurant-reservations/archive/master.zip). Then dump your .po and .mo into /languages to test it.

Once you sign off on the translation, I'll merge the request.

**Comment by scolast34** [comment]
Nate,

 

Sorry it took me some time. Crashed my  dev environment.

I’ve put some stuff on github:

 

·         Settings.class.php Line 533: added __(  ) to make string translatable

·         Restaurant-reservations.pot with new stings

·         Restaurant-reservations.po with fixed translation

·         Restaurant-reservations.mo compiled .po

 

Hope that works for you. I’ll be travelling the next couple of days, so I’ll not be able to do any work on this

 

Cheers

 

Andi

 

Von: Nate Wright [mailto:notifications@github.com] 
Gesendet: Samstag, 3. Januar 2015 12:49
An: NateWr/restaurant-reservations
Cc: scolast34
Betreff: Re: [restaurant-reservations] Create rtbdomain-de_DE.mo (#10)

 

Thanks @scolast34 <https://github.com/scolast34> . I loaded up the files on my end and it looks good. To test all the strings, you can download a copy of the master branch <https://github.com/NateWr/restaurant-reservations/archive/master.zip> . Then dump your .po and .mo into /languages to test it.

Once you sign off on the translation, I'll merge the request.

**Comment by NateWr** [comment]
Duplicate of #9

**Pull request closed without merging**
